---
name: test

on:
  push:
    tags-ignore:
      - "**"
    branches:
      - main
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
  pull_request:
    branches:
      - main

jobs:
  test-unit:
    name: test-unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          path: src/github.com/otaviof/go-get-d
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: test-unit
        env:
          GOPATH: ${{ github.workspace }}
          GO111MODULE: off
        working-directory: src/github.com/otaviof/go-get-d
        run: |
          make
          make test-unit
